name: ezshipp
description: A Delivery app for eZShipp

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.10
  share: ^2.0.4
  line_icons: ^2.0.1
  fluttertoast: ^8.0.8
  image_picker: ^0.8.4+4
  device_info: ^2.0.3
  firebase_core: ^1.10.5
  firebase_messaging: ^11.2.3
  flutter_svg: ^1.0.0
  otp: ^3.0.1
  sms_advanced: ^1.0.1
  sms_autofill: ^2.2.0
  http: ^0.13.4
  google_fonts: ^2.1.0
  intl: ^0.17.0
  google_maps_flutter: ^2.1.1
  flutter_polyline_points: ^1.0.0
  dio: ^4.0.4
  provider: ^6.0.1
  flutter_mobile_vision_2: ^0.1.13
  path_provider: ^2.0.8
  url_launcher: ^6.0.17
  geolocator: ^7.0.3
  signature: ^5.0.0
  places_service: ^0.1.0+2
  geocoder2: ^1.0.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/icon/share/

  
  

  
  

  
  
  
  
